### ISSUE TITLE
CPU is comparatively giving me much faster performance than gpu. Can someone suggest how can I undo that problem?

### ISSUE THREAD

**Issue by kartikeypro** [shreyashankar/m1-setup#1]

**Comment by shreyashankar** [comment]
Hi! Could you be a bit more specific about your issue, like what applications are you trying to run, and have you confirmed that both the cpu and gpu are being used?

**Comment by kartikeypro** [comment]
Oh sorry! I am talking about Jupiter Notebook here. I used the following lines of code to switch to gpu:
-> from tensorflow.python.compiler.mlcompute import set_mlc_device
->set_mlc_device(device_name='gpu')
When I ran an auto encoder on gpu, it trained the model in more time than cpu. Is there any way to resolve this issue? And also how can I get parallel gpu working for training?

**Comment by shreyashankar** [comment]
I'm not sure, but I'll leave the issue open in case anyone else sees it and has an idea. I'd also suggest posting this issue on the tensorflow github.
